### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'node'

### ISSUE THREAD

**Issue by juancarlosfarah** [dit/dit#183]
**Describe the Bug**

I'm getting an error when running one of the [example scripts](https://github.com/dit/dit/blob/master/examples/PID.ipynb) locally inside a `virtualenv`.

The script consists of the following snippet of code, which I have under a file named `pid.py`.

```python
import dit
from dit.pid.helpers import compare_measures
from dit.pid.distributions import bivariates, trivariates
dit.ditParams['print.exact'] = dit.ditParams['repr.print'] = True
dit.ditParams['text.font'] = 'linechar'

for name, dist in bivariates.items():
    compare_measures(dist, name=name)
```

And the error appears to be with the `networkx` package.

```
Traceback (most recent call last):
  File ".../examples/pid.py", line 8, in <module>
    compare_measures(dist, name=name)
  File ".../venv/lib/python3.9/site-packages/dit/pid/helpers.py", line 51, in compare_measures
    vals = [pid.get_partial(node) for pid in pids]
  File ".../venv/lib/python3.9/site-packages/dit/pid/helpers.py", line 51, in <listcomp>
    vals = [pid.get_partial(node) for pid in pids]
  File ".../venv/lib/python3.9/site-packages/dit/pid/pid.py", line 247, in get_partial
    return self._lattice.node[node]['pi']
AttributeError: 'DiGraph' object has no attribute 'node'
```

Running Python v3.9.1 and here are the dependencies installed in the `venv` as shown in the `pip freeze` output.

```
boltons==20.2.1
contextlib2==0.6.0.post1
debtcollector==2.2.0
decorator==4.4.2
dit==1.2.3
networkx==2.5.1
numpy==1.20.2
pbr==5.5.1
prettytable==2.1.0
scipy==1.6.2
six==1.15.0
wcwidth==0.2.5
wrapt==1.12.1
```

**To Reproduce**

- Create a virtualenv with Python 3
```
python3 -m venv venv
```
- Activate the virtualenv
```
source ./venv/bin/activate
```
- Install `dit`
```
pip install dit
```
- Paste the code above into a file (e.g. `pid.py`).
- Run `pid.py`
```
python pid.py
```

**Expected Behavior**

The example from the Jupyter notebook runs as expected.

**Additional Context**

I've seen that other repositories have run into similar problems (e.g. https://github.com/victorlei/smop/issues/165). However, if I try solutions such as pinning `networkx==1.11`, I run into other errors.

```
ImportError: cannot import name 'gcd' from 'fractions' (/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/fractions.py)
```

**Comment by Autoplectic** [comment]
Hi @juancarlosfarah . I think all the networkx compatibility issues are fixed in master. Can you try installing the latest commit and see if that works for you?

**Comment by juancarlosfarah** [comment]
Hi @Autoplectic, indeed installing with `master` solved the DiGraph problem! Here's the output of `pip freeze`:

```
boltons==20.2.1
debtcollector==2.2.0
decorator==4.4.2
dit @ git+https://github.com/dit/dit@c9d206f03d1de5a0a298b1d0ea9d79ea5e789ee1
lattices==0.3.5
networkx==2.5.1
numpy==1.20.2
pbr==5.5.1
PLTable==1.0.2
scipy==1.6.2
six==1.15.0
wrapt==1.12.1
```

Thanks for your help!

I still get the following error running the example code, but I can capture that in a separate issue.

```
ValueError: `x0` violates bound constraints.
```

**Comment by Autoplectic** [comment]
I'm aware of that issue (seen it in the CI), but haven't had a chance to investigate it yet. I think it's due to changes in the `basinhopping` algorithm in scipy. I'll try to get that sorted out in the next few days.

**Comment by juancarlosfarah** [comment]
Thanks for your quick reply. I can open an issue if it helps you with tracking.

**Comment by Autoplectic** [comment]
please do!
